site_name: Modelo Analítico Seguimiento de Proyectos

# Navegación principal de la documentación
nav:
  - Inicio: 
    - Introducción: index.md                     # Página de inicio
    #- Instalación y Configuración: instalacion.md
    #- Conexión a Bases de Datos: conexion_BD.md
    #- Buenas Prácticas: buenaspracticas.md     
  - 1. Conexiones Automáticas a Zoho:
    - 1.1 Configuración de Conexión: 01.Conexiones_Zoho/01.Configuracion_Conexion.md
    - 1.2 ETL de Extracción de Datos: 01.Conexiones_Zoho/02.ETL_Extraccion_Datos.md
  - 2. Conexiones Automáticas a Google Drive:
    - 2.1 Configuración de Conexión: 02.Conexiones_Google_Drive/01.Configuracion_Conexion.md
    - 2.2 ETL de Extracción de Datos: 02.Conexiones_Google_Drive/02.ETL_Extraccion_Datos.md
  - 3. Tablero de Seguimiento de Proyectos:
    - 3.1 Tranformación de Datos para Tablero: 03.Tablero/01.Transformacion_Datos.md
    - 3.2 Modelo Relacional y Medidas: 03.Tablero/02.Modelo_Relacional_Medidas.md
    - 3.3 Visualizaciones:
      - Inicio: 03.Tablero/Visualizaciones/00.Inicio.md
      - Cifras Generales: 03.Tablero/Visualizaciones/01.Cifras_Generales.md
      - Informe por Proyecto y Épicas: 03.Tablero/Visualizaciones/02.Informe_Proyecto_Epicas.md
      - Registro Diario: 03.Tablero/Visualizaciones/03.Registro_Diario.md
      - Reprocesos: 03.Tablero/Visualizaciones/04.Reprocesos.md
      - Comportamiento Histórico: 03.Tablero/Visualizaciones/05.Comportamiento_Historico.md


# Configuración del tema y diseño visual
theme:
  name: material                         # Tema Material para un diseño moderno
  # Indica la ruta relativa al archivo dentro de docs/
  logo: images/logo.png
  # (Opcional) Si no quieres que junto al logo aparezca el nombre del sitio:
  logo_text: true
  highlightjs: true
  language: es                           # Idioma en español para traducciones en el sitio
  features:
    - navigation                  # Expande la navegación del menú lateral
    #- navigation.tabs                   # Usa pestañas de navegación (desactiva si no es necesario)
  palette:
    primary: "23abf7"                   # Color principal personalizado
    accent: "light-blue"                 # Color de acento personalizado
  # icon:
  #   logo: "LogoQCS"  # especifica la ruta del nuevo ícono aquí
  favicon: images/logo_favicon.png               # Imagen personalizada para el favicon del sitio, que se muestra en la pestaña del navegador
# Configuración de plugins de MkDocs
plugins:
  - mkdocstrings
  - search                               # Activa el buscador de la documentación
  - pagetree
  - git-revision-date-localized:
      type: date
      locale: es
# Extensiones Markdown
markdown_extensions:
  - toc:
      permalink: true                    # Agrega enlaces permanentes en el índice de contenido
      toc_depth: 3  # Limita la profundidad del índice a títulos hasta nivel 3 (###)
  - tables                               # Soporte para tablas en Markdown
  - admonition                           # Admoniciones para mensajes resaltados
  - footnotes                            # Soporte de notas al pie
  - def_list                             # Listas de definiciones
  - abbr                                 # Abreviaciones
  - codehilite:
      guess_lang: false                  # Resaltado de sintaxis de código
  - pymdownx.details                     # Soporte para detalles expandibles
  - attr_list                            # Atributos de lista
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - md_in_html                           # Permite HTML dentro de Markdown
  - pymdownx.superfences:                # Superfences para habilitar diagramas Mermaid
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
        - name: M
          class: sql
          format: !!python/name:pymdownx.superfences.fence_code_format
# Archivos adicionales de JavaScript y CSS
extra_javascript:
#  - js/init_mermaid.js                   # Script de inicialización de Mermaid para diagramas
  - javascripts/extra.js


extra_css:
  - css/extra.css                        # Archivo de estilos personalizados para el look & feel

hooks:
  - docs/hooks/copyright.py
copyright: >
  Copyright &copy; {{ anio }} Quality Customer Service &nbsp;|&nbsp;
  <a href="https://drive.google.com/drive/folders/1ChEV4CRcbFDtFibq9ohpMsSas7pg85wX" target="_blank">Fuentes</a> &nbsp;|&nbsp;
  <a href="https://drive.google.com/drive/folders/1ufpdya1F_Pbys_qZ2Q-1zYk7Yfu6VidJ" target="_blank">ETLs</a> &nbsp;|&nbsp;
  <a href="https://drive.google.com/drive/folders/1Cn95SOx5md1JVXtP6Y-WNGX6I3Un39Fz" target="_blank">Tablero Power BI</a>
  <br>
  Última actualización: {{ fecha }}